// Generated by CoffeeScript 1.7.1

/*
  backbone-rest.js 0.5.3
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-rest
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {
  module.exports = require('./rest_controller');

}).call(this);
