// Generated by CoffeeScript 1.9.2

/*
  backbone-rest.js 0.5.3
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-rest
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {
  var BackboneORM, BackboneREST, _, publish;

  _ = (BackboneORM = require('backbone-orm'))._;

  module.exports = BackboneREST = require('./core');

  publish = {
    configure: require('./lib/configure')
  };

  _.extend(BackboneREST, publish);

  BackboneREST.modules = {
    'backbone-orm': BackboneORM
  };

}).call(this);
