// Generated by CoffeeScript 1.6.3
(function() {
  var JoinTableControllerSingleton, RestController, path, _;

  path = require('path');

  _ = require('underscore');

  RestController = null;

  JoinTableControllerSingleton = (function() {
    function JoinTableControllerSingleton() {
      this.join_tables = {};
    }

    JoinTableControllerSingleton.prototype.reset = function() {
      return this.join_tables = {};
    };

    JoinTableControllerSingleton.prototype.generateByOptions = function(app, options) {
      var err, join_table_endpoint, join_table_options, join_table_parts, join_table_url, key, relation, route_parts, route_root, schema, _i, _len, _ref, _ref1, _results;
      if (!RestController) {
        RestController = require('./rest_controller');
      }
      route_parts = options.route.split('/');
      route_parts.pop();
      route_root = route_parts.join('/');
      schema = options.model_type.schema();
      _ref = schema.relations;
      _results = [];
      for (key in _ref) {
        relation = _ref[key];
        if (!(relation && relation.join_table)) {
          continue;
        }
        try {
          join_table_url = _.result(relation.join_table.prototype, 'url');
          join_table_parts = join_table_url.split('/');
          join_table_endpoint = join_table_parts.pop();
        } catch (_error) {
          err = _error;
          console.log("JoinTableControllerSingleton.generateControllers: failed to parse url. Error: " + err);
          continue;
        }
        join_table_options = _.clone(options);
        join_table_options.route = path.join(route_root, join_table_endpoint);
        if (this.join_tables[join_table_options.route]) {
          continue;
        }
        _ref1 = ['white_lists', 'templates', 'default_template'];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          key = _ref1[_i];
          delete join_table_options[key];
        }
        join_table_options.model_type = relation.join_table;
        _results.push(this.join_tables[join_table_options.route] = new RestController(app, join_table_options));
      }
      return _results;
    };

    return JoinTableControllerSingleton;

  })();

  module.exports = new JoinTableControllerSingleton();

}).call(this);
