// Generated by CoffeeScript 1.7.1
(function() {
  var BackboneORM, BackboneREST, _;

  _ = (BackboneORM = require('backbone-orm'))._;

  BackboneREST = require('../core');

  BackboneREST.headers = {
    'Cache-Control': 'no-cache',
    'Content-Type': 'application/json'
  };

  module.exports = function(options) {
    if (options.headers) {
      _.extend(BackboneREST.headers, options.headers);
    }
    return BackboneORM.configure(_.omit(options, 'headers'));
  };

}).call(this);
